[package]
name = "hodlers-circuit"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.100"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
tokio = { version = "1.52" }
alloy-sol-types = "1.4.1"
alloy-primitives = { version = "1.4.1", features = ["serde"] }
wit-bindgen = "0.53.1"

[package.metadata.component]
package = "hodlers-app:circuit"

[profile.release]
opt-level = "s"
lto = true
